version: '3.8'

services:
  toksbay_dev:
    image: postgres:13
    container_name: Esusu_dev
    ports:
      - "5449:5432"
    environment:
      POSTGRES_USER: esusu
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: esusu_dev
    networks:
      - esusu_network

  toksbay_test:
    image: postgres:13
    container_name: esusu_test
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: esusu
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: esusu_test
    networks:
      - esusu_network

networks:
  esusu_network:
    driver: bridge